FROM golang:1.22-alpine3.18

WORKDIR /workdir
COPY ./noblefork /workdir/noblefork

WORKDIR /workdir/noblefork

RUN apk add --no-cache --upgrade bash
RUN apk add --no-cache git
RUN apk add --no-cache make
RUN apk add --no-cache jq

# RUN make build
RUN export CGO_ENABLED=1
RUN LEDGER_ENABLED=false  make build

RUN chmod +x ./play_tf.sh 

ENTRYPOINT ["./play_tf.sh"]

EXPOSE 26657