{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Block_Processing_Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "block_time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total_Tx_Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tmloadtest_coordinator_tx_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total_Tx_Sent",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tmloadtest_coordinator_total_txs",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx_Processing_Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "tx_processing_time", "legendFormat": "__auto" }
   ]
  }
 ]
}