apiVersion: apps/v1
kind: Deployment
metadata:
  name: noblefork
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noblefork
  template:
    metadata:
      labels:
        app: noblefork
    spec:
      containers:
      - name: noblefork
        image: noblefork
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: env-config
        ports:
        - containerPort: 26657
        - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: noblefork-service
spec:
  selector:
    app: noblefork
  ports:
    - protocol: TCP
      port: 26657
      targetPort: 26657
      name: http
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: grpc
  type: LoadBalancer
