apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 2  # Set the number of worker replicas
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: noble-load-worker-v2
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: env-config
