FROM golang:1.20-alpine3.18

WORKDIR /workdir
COPY . /workdir/

RUN apk add --no-cache git

RUN go build -mod=readonly \
    -ldflags "-X github.com/informalsystems/tm-load-test/pkg/loadtest.cliVersionCommitID=`git rev-parse --short HEAD`" \
    -o ./build/tm-load-test ./cmd/tm-load-test/main.go

RUN go build -mod=readonly -o ./build/tm-outage-sim-server ./cmd/tm-outage-sim-server/main.go
RUN chmod +x ./build/tm-load-test

EXPOSE 26670

# CMD ["./build/tm-load-test"]

# RUN cd build && tm-load-test \
#     coordinator \
#     --expect-workers 2 \
#     --bind localhost:26670 \
#     -c 1 -T 10 -r 1000 -s 250 \
#     --broadcast-tx-method async \
#     --endpoints ws://localhost:26657/websocket